# Parameters from
# https://github.com/sgvaze/generalized-category-discovery/blob/main/data/augmentations/__init__.py
# Need to set size to 224x224 for pretrained ViT
_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.Resize
    size: 256
    interpolation: 3  # bicubic
  - _target_: torchvision.transforms.RandomResizedCrop
    size: 224
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.RandomApply
    transforms:
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
    p: 0.8
  - _target_: torchvision.transforms.RandomGrayscale
    p: 0.2
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
